### ISSUE TITLE
识别准确率不行啊，测试图就识别错误了

### ISSUE THREAD

**Issue by gyhua96** [eguid/vlpr4j#1]
String imgPath = "res/image/test_image/plate_judge.jpg";
        opencv_imgcodecs opencv_imgcodecs = null;
        opencv_core.Mat src = opencv_imgcodecs.imread(imgPath);
        String ret=plateRecognise(src); //得到结果 System.err.println(ret);
        System.out.println(ret);

输出的是
        川A0CP56
而实际应为
        苏A0CP56
如下：
![image](https://user-images.githubusercontent.com/15374185/32707640-58f0e3de-c860-11e7-8a11-e2e0c4fad1ed.png)
不知这是什么情况。

**Comment by YOLO777** [comment]
请问一下，我一直报这个错是什么情况，求大神解答，万分感谢
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc310 in java.library.path

**Comment by gyhua96** [comment]
你javacv的包都导入了么？
你的运行环境先说明下吧。
你什么系统？什么开发工具？什么JDK版本

**Comment by YOLO777** [comment]
我用的javacv是源码里的，然后64为系统，用的是IDEA,jdk是1.8

**Comment by eguid** [comment]
好吧，之前确实故意夸大了准确率，真实准确率是79%左右，这是在测试图片的清晰度较为清晰的情况下的准确率，如果图片模糊，对识别准确度的影响是十分大滴。 :）

**Comment by huanmingcn** [comment]
![screenshot from 2018-08-13 23-38-01](https://user-images.githubusercontent.com/13083353/44042085-f3680bd6-9f51-11e8-9228-60eae6003dc6.png)
老郭，你看个大概，20个测试全对一个，惨，不过还是谢谢老哥的项目

**Comment by huanmingcn** [comment]
@gyhua96 老郭，为什么我准确率这么低？你拿了代码之后有改吗?
